#!/usr/bin/env python3
"""G3 -- null controls.

Two experiments that MUST collapse to chance on a healthy dataset:

  1. label shuffle          -- permute y, retrain, AUC must land in [0.45, 0.55]
  2. negatives-only probe   -- train to separate two negative classes generated by the SAME
                               client stack. If this is near-perfect the generators, not the
                               protocols, are being classified.

Neither control existed in v1.
"""
from __future__ import annotations

import numpy as np
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import roc_auc_score

BAND = (0.45, 0.55)


def _fit_auc(X, y, seed=0):
    n = len(y)
    rng = np.random.RandomState(seed)
    idx = rng.permutation(n)
    cut = int(n * 0.75)
    tr, te = idx[:cut], idx[cut:]
    if len(np.unique(y[tr])) < 2 or len(np.unique(y[te])) < 2:
        return float("nan")
    m = HistGradientBoostingClassifier(max_iter=150, learning_rate=0.06,
                                       max_depth=5, random_state=seed).fit(X[tr], y[tr])
    return float(roc_auc_score(y[te], m.predict_proba(X[te])[:, 1]))


def label_shuffle(X, y, seed=0):
    rng = np.random.RandomState(seed)
    return _fit_auc(X, rng.permutation(y), seed=seed)


def negatives_only(X, y_multi, class_a: int, class_b: int, seed=0):
    mask = np.isin(y_multi, [class_a, class_b])
    if mask.sum() < 50:
        return float("nan")
    return _fit_auc(X[mask], (y_multi[mask] == class_a).astype(int), seed=seed)


def run(X, y, y_multi=None, seed=0, verbose=True):
    results = {"label_shuffle_auc": label_shuffle(X, y, seed)}
    if y_multi is not None:
        negs = sorted(int(c) for c in np.unique(y_multi[y == 0]))
        if len(negs) >= 2:
            results["negatives_only_auc"] = negatives_only(X, y_multi, negs[0], negs[1], seed)
            results["negatives_only_pair"] = (negs[0], negs[1])

    ok = BAND[0] <= results["label_shuffle_auc"] <= BAND[1]
    if verbose:
        print(f"  label shuffle AUC        : {results['label_shuffle_auc']:.4f} "
              f"(must be in {BAND})  {'PASS' if ok else 'FAIL'}")
        if "negatives_only_auc" in results:
            a = results["negatives_only_auc"]
            print(f"  negatives-only probe AUC : {a:.4f}  classes {results['negatives_only_pair']}")
            print("    (informational: near 1.0 means the generators, not the protocols, "
                  "are separable -- expected while budget parity is unfixed)")
    results["passed"] = bool(ok)
    return results
